export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_INPROGRESS = "LOGIN_INPROGRESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_INPROGRESS = "LOGOUT_INPROGRESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";